# Generated by Django 5.2.4 on 2025-08-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='record_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dds_app.recordtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(default=1, limit_choices_to={'parent_category__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='dds_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dds_app.recordtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dds_app.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(default=1, limit_choices_to={'parent_category__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sub_records', to='dds_app.category'),
            preserve_default=False,
        ),
    ]
