# Generated by Django 5.2.4 on 2025-08-09 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_app', '0002_alter_category_record_type_alter_record_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dds_app.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_app.recordtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent_category__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='dds_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds_app.recordtype', verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds_app.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'parent_category__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sub_records', to='dds_app.category', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
